export type SourceFigure = {
  image: string;
  caption: string;
  figure: string;
  label: string;
  note?: string;
};

export type ThermalSite = {
  id: string;
  catalogueNo: string;
  romanName: string;
  currentName: string;
  location: string;
  lat: number;
  lng: number;
  zone: 'West' | 'Southwest' | 'Central' | 'South' | 'East';
  temperature: string;
  acidity: string;
  mineral: string;
  waterNote?: string;
  archaeology: string;
  ritual: string;
  sourcePages: string;
  coordinateSource: { label: string; url: string };
  coordinateNote?: string;
  caveat?: string;
  image?: string;
  imageCaption?: string;
  figure?: string;
  plan?: SourceFigure;
  sourceFigures?: SourceFigure[];
  referenceImage?: string;
  referenceCaption?: string;
  referenceSource?: string;
  referenceUrl?: string;
  referenceRights?: string;
  referenceLabel?: string;
  model: {
    pools: number;
    bath: boolean;
    catchment: boolean;
    ritual: boolean;
    confidence: 'documented plan' | 'documented remains' | 'trace only';
  };
};

const commonsImage = (file: string) =>
  `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(file)}`;

const thesisThermalSitesMap: SourceFigure = {
  image: '/archive-plates/thermal-sites-thrace.jpg',
  caption: 'Thermal sites in Thrace, as mapped in the supplied dissertation. This is regional corpus context, not a site plan.',
  figure: 'Fig. 1 · Avramova, supplied dissertation',
  label: 'THESIS CORPUS MAP',
};

export const thermalSites: ThermalSite[] = [
  {
    id: 'pautalia',
    catalogueNo: 'I.1',
    romanName: 'Pautalia',
    currentName: 'Kyustendil',
    location: 'Kyustendil, western Bulgaria',
    lat: 42.281522,
    lng: 22.691661,
    zone: 'West',
    temperature: '74°C',
    acidity: 'pH 8.47',
    mineral: '505 mg/L · moderate',
    archaeology:
      'A spring-side Asclepius setting, architectural elements and mineral-supplied city thermae are documented.',
    ritual:
      'Inscribed bases, votive reliefs, coins and a dense assemblage of objects were recovered at the spring.',
    sourcePages: 'Dissertation pp. 199–203 · printed pp. 195–199',
    coordinateSource: { label: 'Kyustendil thermae record', url: 'https://commons.wikimedia.org/wiki/Category:Roman_thermae_complex_(Kyustendil)' },
    image: '/archive-plates/pautalia-hypocaust.jpg',
    imageCaption: 'Hypocaust under room 1 of the public thermae.',
    figure: 'Fig. 49 · photo by the dissertation author',
    plan: {
      image: '/archive-plates/pautalia-public-thermae-plan.jpg',
      caption: 'Plan of the public thermae.',
      figure: 'Fig. 50 · after Ruseva-Slokoska 2002',
      label: 'SITE PLAN',
      note: 'This plan records the public thermae only; it does not establish a full city-wide reconstruction.',
    },
    sourceFigures: [
      thesisThermalSitesMap,
      {
        image: '/archive-plates/pautalia-hypocaust-sections.png',
        caption: 'Sections of the hypocaust in room 1 of the public thermae.',
        figure: 'Fig. 51 · after Ruseva-Slokoska 2002: 45, fig. 3 · dissertation digital p. 297 / printed p. 293',
        label: 'HYPOCAUST SECTIONS',
        note: 'The sections and the description on printed pp. 89–91 document the heating substructure. They do not establish the heights of the whole bath; the 3D plan keeps vertical dimensions schematic.',
      },
      {
        image: '/archive-plates/pautalia-city-plan.jpg',
        caption: 'Plan of the city and excavated sites.',
        figure: 'Fig. 34 · after Katsarova 2005',
        label: 'CITY PLAN',
      },
      {
        image: '/archive-plates/pautalia-thermae-reservoir-plan.jpg',
        caption: 'The thermae (bottom left) and reservoir (upper right).',
        figure: 'Fig. 36 · after Meshekov 1996',
        label: 'THERMAE CONTEXT',
      },
      {
        image: '/archive-plates/pautalia-keys.png',
        caption: 'Keys recovered from the mineral spring.',
        figure: 'Fig. 88 · after Ivanov 1960',
        label: 'SPRING FIND',
      },
    ],
    referenceImage: commonsImage('RomanThermae-Kiustendil-BG01.jpg'),
    referenceCaption: 'Roman thermae complex at Kyustendil.',
    referenceSource: 'Wikimedia Commons · Gitanes232',
    referenceUrl: 'https://commons.wikimedia.org/wiki/File:RomanThermae-Kiustendil-BG01.jpg',
    referenceRights: 'CC0',
    model: { pools: 2, bath: true, catchment: true, ritual: true, confidence: 'documented plan' },
  },
  {
    id: 'skaptopara',
    catalogueNo: 'I.2',
    romanName: 'Skaptopara',
    currentName: 'Blagoevgrad',
    location: 'Blagoevgrad, western Bulgaria',
    lat: 41.994362,
    lng: 23.052801,
    zone: 'West',
    temperature: '56.2°C',
    acidity: 'pH 8.49',
    mineral: '651 mg/L · moderate',
    waterNote: 'Water properties are from a 1960 well near the spring.',
    archaeology: 'A dry-set catchment built with Roman bricks was observed at one of the springs.',
    ritual: 'Coins span pre-Roman, Roman and later issues; no votive relief is reported.',
    sourcePages: 'Dissertation pp. 204–205 · printed pp. 200–201',
    coordinateSource: { label: 'Vici excavation record', url: 'https://vici.org/vici/67873/' },
    sourceFigures: [thesisThermalSitesMap],
    model: { pools: 0, bath: false, catchment: true, ritual: true, confidence: 'documented remains' },
  },
  {
    id: 'germania',
    catalogueNo: 'I.3',
    romanName: 'Germania',
    currentName: 'Sapareva Banya',
    location: 'Sapareva Banya, southwestern Bulgaria',
    lat: 42.289973,
    lng: 23.268626,
    zone: 'Southwest',
    temperature: '103°C',
    acidity: 'pH 8.8',
    mineral: '650 mg/L · moderate',
    waterNote: 'Properties derive from a main well, not securely from the Roman spring heads.',
    archaeology: 'A western bath is tentatively identified; the eastern zone preserved a catchment, marble spout and lead pipes.',
    ritual: 'Coins and reliefs of Asclepius, Hygieia and Telesphorus are recorded.',
    sourcePages: 'Dissertation pp. 206–208 · printed pp. 202–204',
    coordinateSource: { label: 'DARE ancient-place record', url: 'https://imperium.ahlfeldt.se/places/22369.html' },
    coordinateNote: 'A 2 km-precision ancient-place point, not an excavated bath footprint.',
    plan: {
      image: '/archive-plates/germania-excavation-plan.jpg',
      caption: 'Plan of the 1957 excavations; building III is at lower left.',
      figure: 'Fig. 108 · after Ivanov 1957',
      label: 'EXCAVATION PLAN',
      note: 'The plate documents the excavation footprint, not a complete bath plan or a reconstruction of unexcavated areas.',
    },
    sourceFigures: [
      thesisThermalSitesMap,
      {
        image: '/archive-plates/germania-votive-relief.jpg',
        caption: 'Votive relief dedicated to Asclepius by Ραισκουτούρμη.',
        figure: 'Fig. 107 · after IG Bulg IV 2207',
        label: 'VOTIVE RELIEF',
      },
    ],
    referenceImage: commonsImage('Sapareva_banya_E2.jpg'),
    referenceCaption: 'Sapareva Banya geyser — thermal setting, not Roman masonry.',
    referenceSource: 'Wikimedia Commons · Elena Chochkova',
    referenceUrl: 'https://commons.wikimedia.org/wiki/File:Sapareva_banya_E2.jpg',
    referenceRights: 'CC BY-SA 3.0',
    model: { pools: 1, bath: true, catchment: true, ritual: true, confidence: 'documented remains' },
  },
  {
    id: 'serdica',
    catalogueNo: 'II.1',
    romanName: 'Ulpia Serdica',
    currentName: 'Sofia',
    location: 'Sofia, western Bulgaria',
    lat: 42.699642,
    lng: 23.32277,
    zone: 'West',
    temperature: '46.8°C',
    acidity: 'pH 7.5',
    mineral: '246 mg/L · low',
    archaeology: 'The Roman catchment, bath wall and circular pool survive in the documentary record.',
    ritual: 'A Faustina II coin group and a Nymph relief were recovered by the spring.',
    sourcePages: 'Dissertation pp. 209–211 · printed pp. 205–207',
    coordinateSource: { label: 'Visit Sofia thermal-zone record', url: 'https://visitsofia.info-sofia.bg/en/cityinfrastructure/what-to-see/archaeological-monuments/ancient-serdica-roman-baths-and-a-temple' },
    image: '/archive-plates/serdica-catchment-plan.jpg',
    imageCaption: 'Plan and section of the Roman catchment.',
    figure: 'Fig. 9 · after Bobchev 1964',
    plan: {
      image: '/archive-plates/serdica-catchment-plan.jpg',
      caption: 'Roman catchment of the mineral spring: plan and section.',
      figure: 'Fig. 9 · after Bobchev 1964',
      label: 'CATCHMENT PLAN',
      note: 'The source plate documents the catchment and section, not a complete bath layout.',
    },
    sourceFigures: [thesisThermalSitesMap],
    referenceImage: commonsImage('Archaeological_Complex_Serdica,_Sofia_(P1070778).jpg'),
    referenceCaption: 'Archaeological Complex Serdica — urban archaeological context.',
    referenceSource: 'Wikimedia Commons · Matti Blume',
    referenceUrl: 'https://commons.wikimedia.org/wiki/File:Archaeological_Complex_Serdica,_Sofia_(P1070778).jpg',
    referenceRights: 'CC BY-SA 4.0',
    model: { pools: 1, bath: true, catchment: true, ritual: true, confidence: 'documented plan' },
  },
  {
    id: 'pancharevo',
    catalogueNo: 'II.2',
    romanName: 'Unknown',
    currentName: 'Pancharevo',
    location: 'Sofia City Province, southwestern Bulgaria',
    lat: 42.602391,
    lng: 23.40122,
    zone: 'Southwest',
    temperature: '46.9°C',
    acidity: 'pH unknown',
    mineral: '470 mg/L · low',
    waterNote: 'The catalog notes a present pH of 7.1; the Roman western spring dried after diversion.',
    archaeology: 'Six Roman pools, including a measured 8 × 5 m rectangular pool, were reported; their spatial relationship is unclear.',
    ritual: 'Late Roman coins and two Nymph-relief fragments are recorded.',
    sourcePages: 'Dissertation pp. 212–214 · printed pp. 208–210',
    coordinateSource: { label: 'Pancharevo thermal-bath record', url: 'https://thermalassociation.bg/izvor/mineralna-banya-pancharevo/' },
    coordinateNote: 'Current bath anchor; buried Roman footprint remains uncertain.',
    sourceFigures: [thesisThermalSitesMap],
    referenceImage: commonsImage('Korali-winter5.jpg'),
    referenceCaption: 'Pancharevo’s contemporary mineral-pool setting, not Roman remains.',
    referenceSource: 'Wikimedia Commons · Kralowec',
    referenceUrl: 'https://commons.wikimedia.org/wiki/File:Korali-winter5.jpg',
    referenceRights: 'Public-domain dedication',
    model: { pools: 6, bath: true, catchment: false, ritual: true, confidence: 'documented remains' },
  },
  {
    id: 'momin-prohod',
    catalogueNo: 'II.3',
    romanName: 'Unknown',
    currentName: 'Momin Prohod',
    location: 'Kostenets Municipality, western Bulgaria',
    lat: 42.329077,
    lng: 23.870322,
    zone: 'West',
    temperature: '64°C',
    acidity: 'pH 7.8',
    mineral: '950 mg/L · source says low†',
    waterNote: '†The dissertation’s own threshold would place 950 mg/L in its moderate category.',
    archaeology: 'Two pools are documented at the mineral source.',
    ritual: 'About 45 coins were reported, alongside a Greek-inscribed silver ring.',
    sourcePages: 'Dissertation pp. 215–217 · printed pp. 211–213',
    coordinateSource: { label: 'Momin Prohod bath anchor', url: 'https://www.e-locator.bg/item/%D0%B1%D0%BE%D0%BB%D0%BD%D0%B8%D1%86%D0%B0-%D0%B7%D0%B0-%D1%80%D0%B5%D1%85%D0%B0%D0%B1%D0%B8%D0%BB%D0%B8%D1%82%D0%B0%D1%86%D0%B8%D1%8F-%D0%BC%D0%BE%D0%BC%D0%B8%D0%BD-%D0%BF%D1%80%D0%BE%D1%85%D0%BE/' },
    coordinateNote: 'Current rehabilitation / bath anchor rather than an excavated-plan centroid.',
    sourceFigures: [thesisThermalSitesMap],
    referenceImage: commonsImage('Mineral_water_fountain,_Momin_prohod.jpg'),
    referenceCaption: 'Mineral-water fountain at Momin Prohod — current source setting.',
    referenceSource: 'Wikimedia Commons · Edal Anton Lefterov',
    referenceUrl: 'https://commons.wikimedia.org/wiki/File:Mineral_water_fountain,_Momin_prohod.jpg',
    referenceRights: 'CC BY-SA 3.0 / GFDL',
    model: { pools: 2, bath: true, catchment: true, ritual: true, confidence: 'documented remains' },
  },
  {
    id: 'belchinski-bani',
    catalogueNo: 'II.4',
    romanName: 'Unknown',
    currentName: 'Belchinski Bani',
    location: 'Samokov Municipality, western Bulgaria',
    lat: 42.36732,
    lng: 23.41383,
    zone: 'West',
    temperature: '40°C',
    acidity: 'pH 9.5',
    mineral: '320 mg/L · low',
    waterNote: 'Water data come from a later deep well; the 1932 catchment is no longer used.',
    archaeology: 'Large wooden beams at the Roman level were interpreted as remains of a pool.',
    ritual: 'Trajan coins, rings and marble spouts were recovered; no relief is reported.',
    sourcePages: 'Dissertation pp. 218–220 · printed pp. 214–216',
    coordinateSource: { label: 'Belchinski Bani tourism record', url: 'https://www.tourism.government.bg/en/spa-destinations/6473/6481' },
    coordinateNote: 'Current public bath / spring anchor; no public archaeological-feature coordinate was located.',
    sourceFigures: [thesisThermalSitesMap],
    referenceImage: commonsImage('Mineral-pool-in-Belchinski-Bani.jpg'),
    referenceCaption: 'Mineral pool at Belchinski Bani — current setting.',
    referenceSource: 'Wikimedia Commons · Edal Anton Lefterov',
    referenceUrl: 'https://commons.wikimedia.org/wiki/File:Mineral-pool-in-Belchinski-Bani.jpg',
    referenceRights: 'CC BY-SA 3.0 / GFDL',
    model: { pools: 1, bath: false, catchment: true, ritual: true, confidence: 'trace only' },
  },
  {
    id: 'banya-razlog',
    catalogueNo: 'III.1',
    romanName: 'Unknown',
    currentName: 'Banya, Razlog Municipality',
    location: 'Razlog Municipality, southwestern Bulgaria',
    lat: 41.878144,
    lng: 23.524664,
    zone: 'Southwest',
    temperature: '47.4°C',
    acidity: 'pH 9.30',
    mineral: '234 mg/L · low',
    archaeology: 'Roman walls underlie a later Ottoman structure; pools are described only as possible.',
    ritual: 'An Apollo votive, ancient pottery and a reused inscribed base are recorded.',
    sourcePages: 'Dissertation pp. 221–222 · printed pp. 217–218',
    coordinateSource: { label: 'Destination Razlog site record', url: 'https://destinationrazlog.com/the-old-bulgarian-roman-bath-banya/?lang=en' },
    coordinateNote: 'Published GPS for the current bath site; Roman fabric attribution remains qualified.',
    sourceFigures: [thesisThermalSitesMap],
    model: { pools: 1, bath: true, catchment: false, ritual: true, confidence: 'trace only' },
  },
  {
    id: 'ognyanovo',
    catalogueNo: 'III.2†',
    romanName: 'Unknown',
    currentName: 'Ognyanovo',
    location: 'Garmen Municipality, southwestern Bulgaria',
    lat: 41.612083,
    lng: 23.787583,
    zone: 'Southwest',
    temperature: '40°C',
    acidity: 'pH 9.3',
    mineral: '270 mg/L · low',
    waterNote: '†Printed as a duplicate III.1; rendered here as the apparent intended III.2.',
    archaeology: 'A Roman bath was visible in 1946 but was not excavated.',
    ritual: 'No coins, votives or small finds are recorded in the catalog entry.',
    sourcePages: 'Dissertation pp. 223–224 · printed pp. 219–220',
    coordinateSource: { label: 'Ognyanovo baths-complex record', url: 'https://e-tourguide.eu/bg/place/%D0%BE%D0%B3%D0%BD%D1%8F%D0%BD%D0%BE%D0%B2%D1%81%D0%BA%D0%B8-%D0%BC%D0%B8%D0%BD%D0%B5%D1%80%D0%B0%D0%BB%D0%BD%D0%B8-%D0%B1%D0%B0%D0%BD%D0%B8/' },
    coordinateNote: 'Bath-complex anchor, not a verified pin for the unexcavated Roman bath.',
    sourceFigures: [thesisThermalSitesMap],
    referenceImage: commonsImage('Ognyanovo-Delta-Hotel-Mineral-water-swimming--pools.jpg'),
    referenceCaption: 'Ognyanovo mineral pools — current thermal setting, not Roman remains.',
    referenceSource: 'Wikimedia Commons · Edal Anton Lefterov',
    referenceUrl: 'https://commons.wikimedia.org/wiki/File:Ognyanovo-Delta-Hotel-Mineral-water-swimming--pools.jpg',
    referenceRights: 'CC BY-SA 3.0 / GFDL',
    model: { pools: 1, bath: true, catchment: false, ritual: false, confidence: 'trace only' },
  },
  {
    id: 'bratsigovo',
    catalogueNo: 'IV.1',
    romanName: 'Unknown',
    currentName: 'St. Trinity Spring, Bratsigovo',
    location: 'Bratsigovo Municipality, southern Bulgaria',
    lat: 42.018,
    lng: 24.37,
    zone: 'South',
    temperature: '17.45°C',
    acidity: 'pH 7.3',
    mineral: '254 mg/L · low',
    archaeology: 'No architecture was discovered at the spring.',
    ritual: '170 coins, Late Roman fibulae and bronze hoops were recovered; the sequence is chronologically mixed.',
    sourcePages: 'Dissertation pp. 225–227 · printed pp. 221–223',
    coordinateSource: { label: 'East Aegean Basin source record', url: 'https://earbd.bg/indexdetails.php?elem_id=2540&menu_id=777' },
    coordinateNote: 'General Bratsigovo vicinity only: no authoritative spring / bath pin was found.',
    image: '/archive-plates/bratsigovo-hoops.jpg',
    imageCaption: 'Bronze hoops recovered from the mineral spring.',
    figure: 'Fig. 80 · after Mushmov 1929',
    sourceFigures: [thesisThermalSitesMap],
    model: { pools: 0, bath: false, catchment: false, ritual: true, confidence: 'trace only' },
  },
  {
    id: 'strelcha',
    catalogueNo: 'IV.2',
    romanName: 'Unknown',
    currentName: 'Strelcha',
    location: 'Strelcha Municipality, central Bulgaria',
    lat: 42.506603,
    lng: 24.325861,
    zone: 'Central',
    temperature: '40°C',
    acidity: 'pH 9–9.50',
    mineral: '364 mg/L · low',
    archaeology: 'A brick, tile and lead pipeline and reported bath foundations are recorded.',
    ritual: 'Reliefs of the Nymphs and Heracles are described; the bath foundations lack full documentation.',
    sourcePages: 'Dissertation pp. 228–229 · printed pp. 224–225',
    coordinateSource: { label: 'Strelcha mineral-water record', url: 'https://www.tourism.government.bg/bg/spa-destinations/6499/6510' },
    coordinateNote: 'Spring-use anchor, not an exposed thermae footprint.',
    sourceFigures: [thesisThermalSitesMap],
    referenceImage: commonsImage('Mineral_water_Streltcha_Bulgaria.jpg'),
    referenceCaption: 'Mineral-water fountain at Strelcha — current source setting.',
    referenceSource: 'Wikimedia Commons · Justine.toms',
    referenceUrl: 'https://commons.wikimedia.org/wiki/File:Mineral_water_Streltcha_Bulgaria.jpg',
    referenceRights: 'CC BY-SA 4.0',
    model: { pools: 1, bath: true, catchment: true, ritual: true, confidence: 'documented remains' },
  },
  {
    id: 'diocletianopolis',
    catalogueNo: 'IV.3',
    romanName: 'Diocletianopolis',
    currentName: 'Hisarya',
    location: 'Hisarya Municipality, central Bulgaria',
    lat: 42.500331,
    lng: 24.703631,
    zone: 'Central',
    temperature: '45–48°C',
    acidity: 'pH 8.52–10',
    mineral: '186–266 mg/L · low',
    waterNote: 'Five Roman-used springs are catalogued separately: Toplitsa, Momina salza, Svezhest, Rusalka and Momina banya.',
    archaeology: 'Toplitsa has the Late Antique bath excavated in 1935; Momina salza preserves a catchment and a separate thermal complex.',
    ritual: 'Nymph reliefs, coins, a medical instrument and organic deposits are recorded across the spring complex.',
    sourcePages: 'Dissertation pp. 230–238 · printed pp. 226–234',
    coordinateSource: { label: 'Hisarya Roman thermae record', url: 'https://commons.wikimedia.org/wiki/Category:Roman_Thermae_(Hisarya)' },
    image: '/archive-plates/diocletianopolis-momina-salza.jpg',
    imageCaption: 'Modern catchment at Momina salza within the thermal complex.',
    figure: 'Fig. 12 · photo by the dissertation author',
    plan: {
      image: '/archive-plates/diocletianopolis-late-antique-bath-plan.jpg',
      caption: 'Plan of the Late Antique bath at Toplitsa, excavated by D. Tsonchev in 1935.',
      figure: 'Fig. 15 · after Tsonchev 1937',
      label: 'SITE PLAN',
      note: 'This is the Toplitsa bath (Fig. 15), distinct from the Momina salza thermal complex (Fig. 37) used for the 3D plan relief. The five separately catalogued springs are not combined.',
    },
    sourceFigures: [
      thesisThermalSitesMap,
      {
        image: '/archive-plates/diocletianopolis-thermal-complex-plan.jpg',
        caption: 'Plan of the thermal complex at Momina salza.',
        figure: 'Fig. 37 · after Madzharov, Tancheva, Madzharov 2021a',
        label: 'THERMAL COMPLEX PLAN',
      },
    ],
    referenceImage: commonsImage('Caldarium_pool.jpg'),
    referenceCaption: 'Caldarium pool at the Roman thermae in Hisarya.',
    referenceSource: 'Wikimedia Commons · Rjdeadly',
    referenceUrl: 'https://commons.wikimedia.org/wiki/File:Caldarium_pool.jpg',
    referenceRights: 'CC BY-SA 4.0',
    model: { pools: 5, bath: true, catchment: true, ritual: true, confidence: 'documented plan' },
  },
  {
    id: 'krasnovo',
    catalogueNo: 'IV.5',
    romanName: 'Unknown',
    currentName: 'Krasnovo',
    location: 'Hisarya Municipality, central Bulgaria',
    lat: 42.468283,
    lng: 24.510895,
    zone: 'Central',
    temperature: '56°C',
    acidity: 'pH 9.1',
    mineral: '330 mg/L · low',
    archaeology: 'A pool made from ashlar granite blocks without mortar is recorded.',
    ritual: 'Three Severus Alexander coins and pottery fragments were recovered; no relief is reported.',
    sourcePages: 'Dissertation pp. 239–240 · printed pp. 235–236',
    coordinateSource: { label: 'Krasnovo historic-bath image record', url: 'https://commons.wikimedia.org/wiki/File:3_001.jpg' },
    coordinateNote: 'Historic mineral-bath image anchor; not a confirmed exposed Roman-bath coordinate.',
    caveat: 'The top-level IV.4 is absent from the confirmed catalog; IV.5 is retained as printed.',
    sourceFigures: [thesisThermalSitesMap],
    referenceImage: commonsImage('3_001.jpg'),
    referenceCaption: 'Historic bath building at Krasnovo — locality context.',
    referenceSource: 'Wikimedia Commons · Schumpov',
    referenceUrl: 'https://commons.wikimedia.org/wiki/File:3_001.jpg',
    referenceRights: 'CC BY-SA 3.0',
    model: { pools: 1, bath: false, catchment: false, ritual: true, confidence: 'documented remains' },
  },
  {
    id: 'starozagorski-bani',
    catalogueNo: 'V.1',
    romanName: 'Unknown',
    currentName: 'Starozagorski Bani',
    location: 'Stara Zagora Municipality, central Bulgaria',
    lat: 42.4494,
    lng: 25.494919,
    zone: 'Central',
    temperature: '42°C',
    acidity: 'pH 6.9',
    mineral: '550 mg/L · moderate',
    archaeology: 'Thermae covering about 2,500 m² and two Roman catchments are recorded.',
    ritual: 'Nymph reliefs and dedications to Asclepius, Hygieia and Zeus Dolichenus are recorded.',
    sourcePages: 'Dissertation pp. 241–242 · printed pp. 237–238',
    coordinateSource: { label: 'Stara Zagora municipal record', url: 'https://visitstarazagora.bg/en/place/starozagorski-bani-82' },
    coordinateNote: 'Resort-centre / archaeological-complex anchor rather than an exact excavation centroid.',
    caveat: 'The major 1955–64 excavations remain only partly published.',
    image: '/archive-plates/starozagorski-inscription.jpg',
    imageCaption: 'Building inscription of the thermae.',
    figure: 'Fig. 27 · photo by the dissertation author',
    plan: {
      image: '/archive-plates/starozagorski-thermae-plan.jpg',
      caption: 'Plan of the thermae.',
      figure: 'Fig. 24 · author, based on Nikolov 1968',
      label: 'SITE PLAN',
      note: 'The plan is source evidence for the thermae; height, roofing and unrecorded fabric are not reconstructed.',
    },
    sourceFigures: [
      thesisThermalSitesMap,
      {
        image: '/archive-plates/starozagorski-catchment-gallery-plan.jpg',
        caption: 'Plan of the catchment gallery.',
        figure: 'Fig. 16 · after Tsonchev 1938',
        label: 'CATCHMENT PLAN',
      },
    ],
    referenceImage: commonsImage('Starazagora.mineral.spa-bog.stypka03.JPG'),
    referenceCaption: 'Starozagorski Bani — current resort-area context.',
    referenceSource: 'Wikimedia Commons · Zlatan.Zlatanov',
    referenceUrl: 'https://commons.wikimedia.org/wiki/File:Starazagora.mineral.spa-bog.stypka03.JPG',
    referenceRights: 'Public-domain dedication',
    model: { pools: 3, bath: true, catchment: true, ritual: true, confidence: 'documented plan' },
  },
  {
    id: 'haskovski-mineralni-bani',
    catalogueNo: 'V.2',
    romanName: 'Unknown',
    currentName: 'Mineralni Bani (Haskovo)',
    location: 'Mineralni Bani Municipality, southern Bulgaria',
    lat: 41.941722,
    lng: 25.344194,
    zone: 'South',
    temperature: '57°C',
    acidity: 'pH 6.9',
    mineral: '163 mg/L · low',
    waterNote: 'Four spring groups are described. The listed sulphate value exceeds the listed fixed residue, so the data are flagged.',
    archaeology: 'Four spring groups include pools, baths and three catchments; a pool at the southern group is Roman.',
    ritual: 'Reliefs include Artemis, Nymphs and Silenos; coins span the second through sixth centuries CE.',
    sourcePages: 'Dissertation pp. 243–246 · printed pp. 239–242',
    coordinateSource: { label: 'East Aegean Basin official register', url: 'https://earbd.bg/files/File/Razreshitelni/Registri%20na%20izdadenite%20razreshitelni/2022/28.01/Register_saoraje%20MV_%20BD%20IBR%20_%C2%A7133.pdf' },
    coordinateNote: 'Official borehole / deposit anchor, not an archaeological footprint.',
    image: '/archive-plates/haskovski-stone-spout.jpg',
    imageCaption: 'Stone spout from the first spring group.',
    figure: 'Fig. 33 · after Tsonchev 1940a',
    plan: {
      image: '/archive-plates/haskovski-bath-plan.jpg',
      caption: 'Plan of the bath at the second group of springs.',
      figure: 'Fig. 19 · after Tsonchev 1940a',
      label: 'SITE PLAN',
      note: 'The plate concerns the second spring group and must not be read as a merged plan of all four groups.',
    },
    sourceFigures: [
      thesisThermalSitesMap,
      {
        image: '/archive-plates/haskovski-pool-plan.jpg',
        caption: 'Plan of the pool at the first group of springs.',
        figure: 'Fig. 18 · after Tsonchev 1940a',
        label: 'POOL PLAN',
      },
      {
        image: '/archive-plates/haskovski-group-two-source-page.png',
        caption: 'Complete dissertation plate for the bath at the second group of springs, with the original scale and legend.',
        figure: 'Fig. 19 · after Tsonchev 1940a: 99, fig. 17 · dissertation digital p. 277 / printed p. 273',
        label: 'COMPLETE SOURCE PLATE',
        note: 'The broken lines record water installations. The hatching and open edges do not supply a complete exterior wall footprint; these are not filled into conjectural masonry.',
      },
    ],
    referenceImage: commonsImage('BASA-526K-1-1413-1-Mineralni_Bani,_Bulgaria.JPG'),
    referenceCaption: 'Mineralni Bani in 1940 — locality context.',
    referenceLabel: 'HISTORICAL PHOTOGRAPH',
    referenceSource: 'Wikimedia Commons · Bulgarian Archives State Agency',
    referenceUrl: 'https://commons.wikimedia.org/wiki/File:BASA-526K-1-1413-1-Mineralni_Bani,_Bulgaria.JPG',
    referenceRights: 'Public domain · BASA 526K / inv. 1 / unit 1413 / sheet 1',
    model: { pools: 4, bath: true, catchment: true, ritual: true, confidence: 'documented plan' },
  },
  {
    id: 'aquae-calidae',
    catalogueNo: 'VI.1',
    romanName: 'Aquae Calidae',
    currentName: 'Burgaski Mineralni Bani',
    location: 'Burgas Municipality, eastern Bulgaria',
    lat: 42.6114,
    lng: 27.3937,
    zone: 'East',
    temperature: '41°C',
    acidity: 'pH 9.9',
    mineral: '640 mg/L · moderate',
    waterNote: 'Properties come from a modern well; the Roman spring is no longer harvested and earlier analyses conflict.',
    archaeology: 'Thermae and catchment installations are documented, with excavations continuing in the twenty-first century.',
    ritual: 'A long coin sequence, Nymph reliefs and statue, a Heracles altar, rings and wooden objects were recovered.',
    sourcePages: 'Dissertation pp. 247–249 · printed pp. 243–245',
    coordinateSource: { label: 'Regional Historical Museum Burgas record', url: 'https://www.burgasmuseums.bg/en/encdetail/aqaue-calidae-24' },
    image: '/archive-plates/aquae-calidae-catchment.jpg',
    imageCaption: 'Roman catchment at Aquae Calidae.',
    figure: 'Fig. 21 · Tourist Complex Aquae Calidae Facebook page',
    plan: {
      image: '/archive-plates/aquae-calidae-baths-plan.jpg',
      caption: 'Plan and section of the Roman baths.',
      figure: 'Fig. 20 · after Angelov 1939',
      label: 'SITE PLAN',
      note: 'The source plate records a plan and section of the Roman baths; it is presented as evidence, not as an architectural reconstruction.',
    },
    sourceFigures: [
      thesisThermalSitesMap,
      {
        image: '/archive-plates/aquae-calidae-wooden-box.png',
        caption: 'Wooden box recovered from the mineral spring.',
        figure: 'Fig. 85 · after Mladenova 1961',
        label: 'SPRING FIND',
      },
      {
        image: '/archive-plates/aquae-calidae-comb.jpg',
        caption: 'Wooden comb from the mineral spring.',
        figure: 'Fig. 87 · photo by the dissertation author',
        label: 'SPRING FIND',
      },
    ],
    referenceImage: commonsImage('Aquae_Calidae.jpg'),
    referenceCaption: 'Modern bath house and ancient ruins at Aquae Calidae.',
    referenceSource: 'Wikimedia Commons · Galileo01',
    referenceUrl: 'https://commons.wikimedia.org/wiki/File:Aquae_Calidae.jpg',
    referenceRights: 'CC BY 4.0',
    model: { pools: 3, bath: true, catchment: true, ritual: true, confidence: 'documented plan' },
  },
];

export type DubiousSite = {
  id: string;
  name: string;
  currentName: string;
  location: string;
  lat: number;
  lng: number;
  zone: 'West' | 'Southwest' | 'Central' | 'South' | 'East';
  reason: string;
  sourcePages: string;
};

// These records are intentionally not treated as confirmed thermal sites.
// Their map coordinates show the modern locality context only, never a claimed Roman footprint.
export const dubiousSites: DubiousSite[] = [
  {
    id: 'banya-panagyurishte',
    name: 'Banya, Panagyurishte Municipality',
    currentName: 'Banya',
    location: 'Pazardzhik Province · locality context only',
    lat: 42.509,
    lng: 24.225,
    zone: 'Central',
    reason: 'No Roman finds were recorded from the springs; nearby Roman sites alone do not confirm thermal use.',
    sourcePages: 'Dissertation p. 250 · printed p. 246',
  },
  {
    id: 'beden',
    name: 'Beden',
    currentName: 'Beden, Devin Municipality',
    location: 'Smolyan Province · locality context only',
    lat: 41.688,
    lng: 24.399,
    zone: 'South',
    reason: 'A primitive catchment and bath foundations are described, but their Roman date is unproven.',
    sourcePages: 'Dissertation p. 251 · printed p. 247',
  },
  {
    id: 'dobrinishte',
    name: 'Dobrinishte',
    currentName: 'Dobrinishte, Bansko Municipality',
    location: 'Blagoevgrad Province · locality context only',
    lat: 41.815,
    lng: 23.567,
    zone: 'Southwest',
    reason: 'Reports of “Roman masonry” and pools lack corroborating Roman settlement or artefact evidence.',
    sourcePages: 'Dissertation p. 252 · printed p. 248',
  },
  {
    id: 'merichleri',
    name: 'Merichleri',
    currentName: 'Merichleri, Dimitrovgrad Municipality',
    location: 'Haskovo Province · locality context only',
    lat: 41.632,
    lng: 25.139,
    zone: 'South',
    reason: 'A reported Nymph relief has uncertain provenance; the surviving basin is not Roman and the spring later dried up.',
    sourcePages: 'Dissertation pp. 253–254 · printed pp. 249–250',
  },
  {
    id: 'banya-sliven',
    name: 'Banya, Sliven Municipality',
    currentName: 'Novozagorski Mineralni Bani / Kortenski Bani',
    location: 'Nova Zagora area · locality context only',
    lat: 42.401,
    lng: 26.0,
    zone: 'Central',
    reason: 'The locally named “Roman bath” is identified as Ottoman; older catchments and coins lack sufficient dating detail.',
    sourcePages: 'Dissertation pp. 255–256 · printed pp. 251–252',
  },
  {
    id: 'pavel-banya',
    name: 'Pavel Banya',
    currentName: 'Pavel Banya',
    location: 'Stara Zagora Province · locality context only',
    lat: 42.597,
    lng: 25.206,
    zone: 'Central',
    reason: 'Claims of Roman slabs, foundations and baths come from non-archaeological publications and remain uncorroborated.',
    sourcePages: 'Dissertation p. 257 · printed p. 253',
  },
  {
    id: 'slivenski-mineralni-bani',
    name: 'Slivenski Mineralni Bani',
    currentName: 'Dzhinovski Mineralni Bani',
    location: 'Sliven Province · locality context only',
    lat: 42.665,
    lng: 26.355,
    zone: 'Central',
    reason: 'Traditional reports of Roman pools, wells and coins are too sparse to confirm a Roman thermal site.',
    sourcePages: 'Dissertation pp. 258–259 · printed pp. 254–255',
  },
  {
    id: 'traianopolis',
    name: 'Traianopolis',
    currentName: 'Loutra Traianoupoleos',
    location: 'Evros, Greece · locality context only',
    lat: 40.845,
    lng: 25.884,
    zone: 'South',
    reason: 'Only an Ottoman bath is visible; coins, healing iconography and a physician’s grave are indirect evidence.',
    sourcePages: 'Dissertation p. 260 · printed p. 256',
  },
  {
    id: 'varvara',
    name: 'Varvara',
    currentName: 'Varvara, Septemvri Municipality',
    location: 'Pazardzhik Province · locality context only',
    lat: 42.103,
    lng: 24.156,
    zone: 'South',
    reason: 'A sanctuary is close to a karst spring, not the mineral springs; mineral-water use in the Roman period is only possible.',
    sourcePages: 'Dissertation p. 261 · printed p. 257',
  },
  {
    id: 'velingrad',
    name: 'Velingrad',
    currentName: 'Velingrad',
    location: 'Pazardzhik Province · locality context only',
    lat: 42.028,
    lng: 23.99,
    zone: 'South',
    reason: 'Roman channels were recorded, but no bath or secure spring-use context was excavated.',
    sourcePages: 'Dissertation p. 262 · printed p. 258',
  },
  {
    id: 'yagoda',
    name: 'Yagoda',
    currentName: 'Yagoda, Maglizh Municipality',
    location: 'Stara Zagora Province · locality context only',
    lat: 42.65,
    lng: 25.925,
    zone: 'Central',
    reason: 'The strongest dubious case: reports of pools and finds are compelling but lack secure spring provenance.',
    sourcePages: 'Dissertation p. 263 · printed p. 259',
  },
];
